export const listData = [
    {
        id: 1,
        title: 'Cho thuê căn hộ chung cư 3 phòng ngủ',
        location: 'Cầu Giấy, Hà Nội',
        bedrooms: 3,
        bathrooms: 2,
        area: 127.3,
        floor: 13,
        price: '71,000,000',
        priceType: 'rent',
        features: ['Swimming pool', 'Air conditioning', 'Gym', 'Internet', 'Security', 'Car park'],
        images: [
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTFkNjUzLTZjMzQtN2NjYS05NzMxLTcyZDdlNTA0MDZlZC8wMTkxZDY1My04ZWJhLTcyY2UtOGFkNy05NjY0OTMzNWJmMWMuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTE3ZTMwLThlMGQtNzIyNi1hMWQ2LTUwZTgyZTVjYjViYi8wMTkxN2UzMC04Zjc1LTcxMjUtODVhMC01YTIzNjVkZWU4NDQuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
        ],
        isNew: true,
    },
    {
        id: 2,
        title: 'Căn bán căn hộ chung cư 1 phòng ngủ',
        location: 'Thủ Dầu Một, Bình Dương',
        bedrooms: 1,
        bathrooms: 1,
        area: 60,
        floor: 11,
        price: '2.88 tỷ',
        priceType: 'buy',
        features: ['Air conditioning', 'Car park', 'Balcony', 'Built-in wardrobe'],
        images: [
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTE3ZTMwLThlMGQtNzIyNi1hMWQ2LTUwZTgyZTVjYjViYi8wMTkxN2UzMC05MDMzLTczOTctYmZmYi02NDAwMmJmYTg2YTYuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTE3ZDgxLTQzZTMtNzk5My04MzIzLTg5MmI0Y2YyNjhmYi8wMTkxN2VhMi1kOGY3LTcwNTQtOTEzOS0wZjAxYzNjNmZhMWQuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
        ],
        isNew: false,
    },
    {
        id: 3,
        title: 'Cho thuê căn hộ chung cư 3 phòng ngủ',
        location: 'Hà Nội',
        bedrooms: 3,
        bathrooms: 2,
        area: 127.3,
        floor: 13,
        price: '71,000,000',
        priceType: 'rent',
        features: ['Swimming pool', 'Air conditioning', 'Gym', 'Internet', 'Security', 'Car park'],
        images: [
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTFkNjUzLTZjMzQtN2NjYS05NzMxLTcyZDdlNTA0MDZlZC8wMTkxZDY1My04ZWJhLTcyY2UtOGFkNy05NjY0OTMzNWJmMWMuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
            'https://pix.dotproperty.co.th/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJwcm9wZXJ0aWVzLzAxOTE3ZTMwLThlMGQtNzIyNi1hMWQ2LTUwZTgyZTVjYjViYi8wMTkxN2UzMC04Zjc1LTcxMjUtODVhMC01YTIzNjVkZWU4NDQuanBnIiwiYnJhbmQiOiJET1RQUk9QRVJUWSIsImVkaXRzIjp7InJlc2l6ZSI6eyJ3aWR0aCI6NDkwLCJoZWlnaHQiOjMyNSwiZml0IjoiY292ZXIifX19',
        ],
        isNew: true,
    },
];
